name: 'Get Last Active Deployment Action'
description: Find the (nth) last active deployment for a given GitHub environment.
author: 'Adventure Tech AS'

# Define your inputs here.
inputs:
  github-token:
    description: 'A github token used to create the release'
    required: false
    default: ${{ github.token }}
  environment:
    description: 'The environment of the deployment (e.g. production-my-app)'
    required: true
  repository:
    description: 'Repository to search'
    required: false
    default: ${{ github.repository }}
  nth:
    description: 'Find the nth successful deployment'
    required: false
    default: 1

# Define your outputs here.
outputs:
  deployment-id:
    description: 'The GitHub Id of the deployment'
  deployment-sha:
    description: 'The sha of the commit that was deployed'
  deployment:
    description: 'The deployment object as stringified JSON'

runs:
  using: node20
  main: dist/index.js
