name: 'Turbo Monorepo Release Action'
description: |
  Creates a GitHub release from a commit range.
  Filters the commit range by two criteria:

  1. The commits must match conventional commit format
  2. The commits must trigger a turbo build for the workspace

  Commit range is start (exclusive) to end (inclusive).
  The first commit should be the commit preceding the first commit in the release.
author: 'Adventure Tech AS'

# Define your inputs here.
inputs:
  github-token:
    description: 'A github token used to create the release'
    required: false
    default: ${{ github.token }}
  environment:
    description: 'The environment of the deployment (e.g. production-my-app)'
    required: true
  repository:
    description: 'Repository to search'
    required: false
    default: ${{ github.repository }}
  nth:
    description: 'Find the nth successful deployment'
    required: false
    default: 1

# Define your outputs here.
outputs:
  deployment-id:
    description: 'The GitHub Id of the deployment'
  deployment-sha:
    description: 'The sha of the commit that was deployed'
  deployment:
    description: 'The deployment object as stringified JSON'

runs:
  using: node20
  main: dist/index.js
